export const GET_MENUITEMS = "UPDATE_MENUITEMS";
export const REMOVE_MENUITEM = "REMOVE_MENUITEM";
//export const SET_CURRENT_MENUITEM = "SET_CURRENT_MENUITEM";
export const ADD_MENUITEM = "ADD_MENUITEM";
export const LOADING = "LOADING";
export const UPDATE_MENUITEM = "UPDATE_MENUITEM";
//export const REMOVE_MENUITEM = "REMOVE_MENUITEM";